### ISSUE TITLE
Diff highlight for translation conflicts

### ISSUE THREAD

**Issue by trungams** [jonatanklosko/internationalize#10]
Hi Jonatan,

I forgot to take a screencap. But for longer sentences that needs updating in the app, sometimes it's really hard to spot the changes, and I often get too tired to just rewrite the translation (it might affect consistency too). So I'm thinking if you can highlight the changed words/phrases for each conflict? I may be able to work on this, but disclaimer: I'm very new to Javascript, assuming it's used to tackle this issue.

Trung

**Comment by jonatanklosko** [comment]
Hey Trung, I gave it a shoot in https://github.com/jonatanklosko/internationalize/commit/0c30ecc90ed07e75cc929a68ea8b285738c6cb9f. Now the synchronization dialog shows both diff and new original text, so you can use both to figure out what to change. Next time you resolve some conflicts, please let me know if that's what you had in mind =)

**Comment by trungams** [comment]
Thanks for the quick response! I'll let you know soon.

**Comment by trungams** [comment]
Hey, I got back to translating after a while, and just want to say the change looks good. Well done :grinning:
