### ISSUE TITLE
Use multiline text boxes for translation input

### ISSUE THREAD

**Issue by trungams** [jonatanklosko/internationalize#11]
This is just a suggestion to improve the experience a bit :stuck_out_tongue: If a multiline box is used (is it called textarea?) we won't have to scroll back and forth when we want to proofread a paragraph.

Screenshot of the current input box:

![image](https://user-images.githubusercontent.com/25715630/52906754-e3944c80-3220-11e9-8768-23674d714d79.png)

**Comment by jonatanklosko** [comment]
The thing about textarea is that it handles new lines, so clicking enter would add new line instead of submitting the translation. I will look into overriding that default behaviour and see how it goes.

**Comment by jonatanklosko** [comment]
Implemented in 8e0502a42f35598bf3a04287675a9d09cbe7c85d. Thanks for suggesting that :tada: :ship:

**Comment by trungams** [comment]
Seems like there's still this line to be updated. The default enter behaviour is not ignored anymore after my first translation

https://github.com/jonatanklosko/internationalize/blob/8e941b95c2a432f4f7835d681377d7e49fb731f8/client/app/views/translations/show/translate/translate.view.html#L17

**Comment by jonatanklosko** [comment]
Hmm, it does work for me, what browser do you use? Do you see any errors in the dev console? The line you mentioned only renders a component, whereas the textarea is handled within that component.

**Comment by trungams** [comment]
Oh yeah my bad I did not see the html tag

I'm on Firefox 65.0 and got this error in my console: 
![image](https://user-images.githubusercontent.com/25715630/52919418-3ed14800-32d0-11e9-867b-d03af0947d10.png)

**Comment by jonatanklosko** [comment]
Oh wow, that's a pretty valid error, now I have no idea why it did work in Chrome in the first place! Fixed in 45eed35588c7bfea8f2cb610545b21cec5959e37.

**Comment by trungams** [comment]
Haha. Thanks for your work!
