### ISSUE TITLE
How do you change your password?

### ISSUE THREAD

**Issue by jfly** [jonatanklosko/internationalize#29]
Is this supported? I haven't been able to find a button anywhere on the UI, and it doesn't look like there are any API routes for it: https://github.com/jonatanklosko/internationalize/blob/72436c675f33e0ab7da7533b0ee44a9386587427/server/config/routes.js#L31-L36

**Comment by jonatanklosko** [comment]
Hey, yeah it's not supported, the app doesn't actually collect emails or anything. FWIW I don't think it's crucial for our use case because people submit their work into the GitHub repo, so they can always create a new account and import it.

**Comment by jfly** [comment]
That makes sense!
