### ISSUE TITLE
Synchronization with WCA remote no longer works, WCA locales moved

### ISSUE THREAD

**Issue by viktorzenk** [jonatanklosko/internationalize#33]
Synchronization with remote no longer works for me, I'm getting 404 error on GET https://raw.githubusercontent.com/thewca/worldcubeassociation.org/master/WcaOnRails/config/locales/en.yml.

I think it has to do with [this PR](https://github.com/thewca/worldcubeassociation.org/pull/8945) in the worldcubeassociation repo, where some files have moved. The locales now seem to be located at https://raw.githubusercontent.com/thewca/worldcubeassociation.org/master/config/locales/en.yml.

**Comment by jonatanklosko** [comment]
Hey @viktorzenk, you are correct. You can Edit the given translation and update the URLs (in this case just remove `WcaOnRails`).

**Comment by viktorzenk** [comment]
Wow, quick response! Yeah I realize this is not exactly an issue with the Internationalize app, but rather a configuration that needs to be done on the user side. I have now updated the URL and it's working for me.
This probably needs to be communicated to WCA translators, but that's outside of the scope for this app.
Thanks!

**Comment by jonatanklosko** [comment]
Sounds good, I will send an email to the group!
